### ISSUE TITLE
Administrator's Guide

### ISSUE THREAD

**Issue by luutuntin** [kawu/contemplata#136]
Dear Contemplate team,

We are planning to use Contemplate to manually revise constituency trees for [our project](http://birch.ling.brandeis.edu/). We can find the installation instructions on this GitHub site and the user's guide [here](http://vega.info.univ-tours.fr/odil/current/user/guide). We wonder whether we can find an administrator's guide (in addition to the information mentioned in [the Contemplata paper](https://www.aclweb.org/anthology/2020.lrec-1.892.pdf)). We also appreciate any additional guidance from your team.

Best,
Alex

**Comment by kawu** [comment]
Dear Alex,

Thank you for your interest!  I also apologize for a late reply, I was on holiday at the moment you filed the issue.

To answer your question, I'm afraid the administrator's guide is not particularly complete at the moment.  Apart from the Contemplata paper you already mentioned, there's a short description of the configuration of the tool [in the repository](https://github.com/contemplata/contemplata/blob/master/config/README.md).  An example configuration (similar to the one we used for our original annotation project) can be found in the [dhall subdirectory](https://github.com/contemplata/contemplata/tree/master/config/dhall).  If you have question regarding the contents of this directory, don't hesitate to let me know.

Good luck with your project!

Best,
Jakub

**Comment by luutuntin** [comment]
Thank you so much, Jakub. We will keep in touch with you.

**Comment by luutuntin** [comment]
Dear Jakub, I'm experimenting with the front-end interface and having some questions:

- How can we download a file? Or can we only access the files from the back-end database?
- Are there any publicly accessible files (JSON and/or GLOZZ) we can use to test?

When I try to convert a parsed file from the Penn Tree Bank (wsj_0001.prd) into Contemplata's JSON format, I get the following error:

![convert_error](https://user-images.githubusercontent.com/11186240/116762351-27ca2c80-a9e8-11eb-9a42-00a4c1ab3097.png)

I don't know whether the error is caused by the file itself or there is some problem in our installation of Contemplata.

**Comment by luutuntin** [comment]
Actually, **_penn2json_** works when I put one tree per line in the input file. Are there other useful pieces of information we should know?

**Comment by kawu** [comment]
Dear Alex, as far as I remember, the administrator is allowed to download files directly from the website but I have to check (I should have some spare time to do that on Wednesday).  Would it be interesting for you to give this option to regular users as well?  I can also prepare some sample JSON files, although I see that you managed to get `penn2json` working.  You are right, the script requires each tree to be in a separate line (I will add a mention about that in the README).

**Comment by luutuntin** [comment]
Dear Jakub,

After managing to convert a PTB file into the JSON file, I played around with the administrator's interface and somehow crashed the web application (the error is "504 Gateway Time-out" and I will need some help from our system administrator to fix it). That's why I haven't found out how to download files as an admin. But yes, I have a strong feeling that the admin is allowed to do that.

As a regular user, I would love to be able to download files too, at least in case I want to have a backup version on my computer. As per my observation, our annotators feel more secure when they can back up their work and feel like they won't loose anything even if the server crashes.

In the paper, you mention that JSON files can be later converted to an annotation-specific format. Have you done that for your project? I'm especially interested in converting back to PTB.

Best,
Alex

**Comment by kawu** [comment]
Dear Alex,

I hope the crash wasn't serious, normally Contemplata should be pretty stable!  Did you try doing something unusual?

Concerning downloading JSON files, I've just checked and indeed the admin can do that (go to the `Files` tab, select the file you want to download, and click `Show JSON` in the `General information` section).  I will also see if I can add this option for regular users in the next few days.

Otherwise, the method I often use with Contemplata to make sure that no files get lost is to have a central repository with the database and set up a cron job to systematically submit the changes from the version on the server to this central repository.  This way, as an administrator, you can have another local copy of the repository and just pull all the changes every now and then to have the latest annotations on your own disk.

Concerning the conversion from JSON to annotation-specific formats, I didn't participate in this part of the project, but I could ask.  In any case, if what you are interested in is converting back to PTB (i.e. bracketed format), then I should be able to easily add this functionality.

Best,
Jakub

**Comment by luutuntin** [comment]
Thank you so much, Jakub. This week is the last study week of the Spring semester here, and I need to prioritize other commitments. I'll keep you posted about the crash (I just basically clicked this, clicked that and it happened). And look forward to your new updates.

**Comment by luutuntin** [comment]
Dear Jakub, when I try to open the JSON file I have converted from a PTB file on Contemplata, I can only see this:

![image](https://user-images.githubusercontent.com/11186240/123865747-4c645700-d8fa-11eb-85e0-0445374eefc4.png)

I put both files, the original PTB and the corresponding JSON, in the attached zipped folder in case you want to take a look at them. It will be great if you can send me some sample JSON files.
 
[wsj_0001_one_segment_per_line.zip](https://github.com/contemplata/contemplata/files/6736362/wsj_0001_one_segment_per_line.zip)

**Comment by kawu** [comment]
Dear Alex, I'm sorry for a late reply, unfortunately I am very busy these days...  Concerning your question, I had no trouble uploading your file to my local Contemplata instance and then opening it in the annotation interface.  Does it work for you on your local computer?

Could you also please tell me what the contents of your `devel.cfg` file are?

**Comment by kawu** [comment]
(in particular, look for the attribute `base` in `devel.cfg`, which needs to be updated for each instance of contemplata.  I might have forgot to mention that in the README :/)

**Comment by luutuntin** [comment]
Thank you, Jakub. The current contents of our `devel.cfg` file are the same as [your default `devel.cfg`](https://github.com/contemplata/contemplata/blob/master/config/devel.cfg).

For example, if the URL of our instance of Contemplata is `https://example.brandeis.edu`, should we update the contents of our `devel.cfg` file as below?

> base = "example.brandeis.edu"
> href-base = "https://$(base)/"
>

**Comment by kawu** [comment]
Yes, exactly.

The next step is to make sure that the websocket connection is established.  One way of doing that is to toggle web console (on my Firefox: Tools -> Developer -> Web console) and see if there are any messages related to that.  For instance, if I change the websocket address to an invalid one with my local contemplata instance, I get the following error messages in Web console:
```
Firefox can’t establish a connection to the server at ws://localhost:8000/ws123. main.js:10172:16
Firefox can’t establish a connection to the server at ws://localhost:8000/ws123. main.js:10172:16
Firefox can’t establish a connection to the server at ws://localhost:8000/ws123. main.js:10172:16
...
```
and contemplata is blocked on a blank page with the "Fetching annotation configuration" message.
